<!--
%\VignetteEngine{knitr}
%\VignetteIndexEntry{BDL ANOVA}
-->

## Read BDL data
The BDL data, BDL sample definition and the Fluidigm probe definitions are loaded via
```{r BDLdata, eval=TRUE}
library('reshape')
library("calibrate")
library('BDLanalysis')
data(BDLdata)
data(BDLsamples)
data(BDLprobes)
```

Additional reshaping of the individual factors for ANOVA
```{r BDLmatrix}
BDLmatrices <- bdl_matrix_data(BDLdata, BDLsamples)
print(BDLmatrices[[1]])
```

## Dimension reduction via ANOVA
Dimension reduction of the factors is performed by ANOVA testing for significant
difference in the time course. 
```{r ANOVA}
# calculate anova
df.anova <- all_factor_anova()
df.anova$sig <- sapply(df.anova$p.value, significant_code)

# Adjust the p-values for multiple testing
# Given a set of p-values, returns p-values adjusted using one of several methods.
# The Bonferroni, Holm, Hochberg, Hommel are designed to give strong control of the family-wise error rate. There seems no reason to use the unmodified Bonferroni correction because it is dominated by Holm's method, which is also valid under arbitrary assumptions. 
# Using Holm correction with number of tests.
# Holm, S. (1979). A simple sequentially rejective multiple test procedure. Scandinavian Journal of Statistics 6, 65–70.
df.anova$p.holm <- p.adjust(df.anova$p.value, method ="holm" , n = length(df.anova$p.value))
df.anova$sig.holm <- sapply(df.anova$p.holm, significant_code)

# save the ordered results of the ANOVA test
df.anova.ordered <- df.anova[with(df.anova, order(p.holm)), ]
summary(df.anova.ordered)
write.table(df.anova.ordered, file="../results/factor_anova.csv", sep="\t", quote=FALSE)

# file.anova <- file.path("..", "data", "bdl-anova.Rdata")
# save(df.anova, file=file.anova)
```
